# Github workflow to build docker container
name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ericellb/what-should-i-wear .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Push the Docker image to the repository
        run: docker push ericellb/what-should-i-wear
  build-exe:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make Path to Artifact
        run: mkdir -p binaries
      - name: Install Deps
        run: npm install
      - name: Cache the node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Build the exe
        run: npm run build:exe:win
      - name: Upload the exe
        uses: actions/upload-artifact@v3
        with:
          name: what-should-i-wear
          path: ./binaries/node-test-app.exe
